import Matrix from "../matrix";
export declare function fail(message: string): void;
export declare function assertFalse(bool: boolean, msg: string): void;
export declare function assertTrue(bool: boolean, msg: string): void;
export declare function assertMatrixEquals(expected: Matrix, result: Matrix): void;
export declare function assertNumEquals(expected: number, result: number): void;
export declare function assertArrayEquals(expected: any[], result: any[]): void;
export declare function assertNumNotEquals(expected: number, result: number): void;
export declare function assertGreaterThan(num: number, min: number): void;
export declare function assertLesserThan(num: number, min: number): void;
